model: &base_model
  data_dir: "raw_data/"
  out_data_dir: "processed_data/"
  output_dir: "doc/latex/figure/"
  model_out_dir: "models/"
  random_seed: 42
  # ==== Data Processing ====
  sensor_loc:
    - "waist"
    - "ankle"
    - "wrist"
  ft_col:
    - "x"
    - "y"
    - "z"
    # - "vm"
  extracted_features:
    - "mean"
    - "std"
  classes:
    - "downstairs"
    - "jog_treadmill"
    - "upstairs"
    - "walk_treadmill"
    # - "walk_mixed"
    # - "walk_sidewalk"
  window_size: 100
  stride: 5
  save_pkl: False
  
# ==== Model Training ====
random_forest:
  <<: *base_model
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

transformer:
  <<: *base_model
  test_size: 0.2
  batch_size: 64
  patience: 20
  learning_rate: 0.0015
  weight_decay: 0.001
  epochs: 2
  d_model: 66
  fc_hidden_dim: 128
  nhead: 6
  num_layers: 2
  dropout: 0.1
  load_model_path: ''

  # learning_rate: 0.0015
  # weight_decay: 0.00
  # epochs: 60
  # d_model: 260
  # fc_hidden_dim: 512
  # nhead: 6
  # num_layers: 3
  # dropout: 0.15
  # load_model_path: ''

    # NOTE:
    # self.head_dim * num_heads == self.embed_dim