name: har
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - scikit-learn
  - wandb
  - matplotlib
  - tqdm
  - numpy
  - seaborn
  - scipy
  - pandas
  - pytorch
  - pytest
